### ISSUE TITLE
accessing request object in method field?

### ISSUE THREAD

**Issue by philippeluickx** [clarkduvall/serpy#12]
I provide data based on the user that is currently authenticated.
With DRF I simply access self.context.request. I see the serializer accepts the context object, but leaves it at None. Is this a choice by design or a feature to be implemented?
Dealbreaker for me in any case.

In terms of performance testing, FYI I am getting 50% gains compared to DRF. Which is significant and would be great to have in prod...!

**Comment by clarkduvall** [comment]
The context argument was added to the constructor to be compatible with DRF generic views and is currently not used. You can make a custom base serializer that sets the context, and then you'll be able to access it later:

```py
class BaseSerializer(Serializer):
    def __init__(self, instance=None, many=False, data=None, context=None, **kwargs):
        self.context = context
        super(BaseSerializer, self).__init__(instance, many, data, context, **kwargs)

# Then in your serializer:
class MySerializer(BaseSerializer):
    foo = MethodField()

    def get_foo(self, obj):
        # Access self.context

>>> MySerializer(obj, context=context).data
```

Glad you're seeing significant performance gains!

**Comment by philippeluickx** [comment]
Thanks, will try that!
