### ISSUE TITLE
Question: RelatedManager (Django)

### ISSUE THREAD

**Issue by MrChoclate** [clarkduvall/serpy#13]
I currently do an ugly hack to serialize object with a RelatedManager attribute.

I got two objects. House and Door. A house have several doors. I want to serialize an house with nested serialization. 

```python
home.doors = home.door_set.all()
data = HomeSerializer(home).data
```

I mainly do this because RelatedManager is not iterable. Do you have a better way?
I would like to use the same serializer for a Door and for a RelatedManager of Door. 
```python
class HomeSerializer(serpy.Serializer):
    door_set = DoorSerializer(many=True)  # Does not work
```

But I could not find a proper way to do this. I only start using your lib (which is awesome btw !) yesterday, so I may be missing something.

It would be great if you can add an example of object with RelatedManager attribute in the documentation.

**Comment by clarkduvall** [comment]
One way to do this is:

```py
class HomeSerializer(serpy.Serializer):
    door_set = DoorSerializer(many=True, call=True, attr='door_set.all')
```

Let me know if that works for you. You're right, this would be a good addition to the docs.

**Comment by MrChoclate** [comment]
Very nice ! It works, thank you.
