### ISSUE TITLE
Context is not set on serializers

### ISSUE THREAD

**Issue by ahankinson** [clarkduvall/serpy#16]
There is a context keyword argument, but values passed there are not set on the object.

See: https://github.com/clarkduvall/serpy/blob/master/serpy/serializer.py#L87

**Comment by clarkduvall** [comment]
The context argument was added for compatibility with Django REST Framework (#7), but it isn't actually used anywhere, so it's just ignored. If you need to use it I recommend making a custom Serializer subclass that sets context on the object.

**Comment by ahankinson** [comment]
That's what I'm doing now:

```
class ContextSerializer(serpy.Serializer):
    def __init__(self, *args, **kwargs):
        super(ContextSerializer, self).__init__(*args, **kwargs)
        if 'context' in kwargs:
            self.context = kwargs['context']
```

If it's a design decision that the context argument is going to be ignored, perhaps a note in the documentation to this effect would be possible?
