### ISSUE TITLE
MethodField's staticmethod expects self parameter, unused and inconsistent with DRF

### ISSUE THREAD

**Issue by davidtgq** [clarkduvall/serpy#23]
Django Rest Framework's SerializerMethodField expects something like this:

```
@staticmethod
def get_field(data):
    return ret
```

Whereas Serpy requires the self parameter:

```
@staticmethod
def get_field(self, data):
    return ret
```

**Comment by vesterbaek** [comment]
Think you are mistaken here: http://www.django-rest-framework.org/api-guide/fields/#serializermethodfield

**Comment by davidtgq** [comment]
You're right, I figured it out a while ago but forgot to delete this, sorry
