### ISSUE TITLE
Non-required key raises key error when not present

### ISSUE THREAD

**Issue by ahankinson** [clarkduvall/serpy#51]
In serpy 0.2, if a field set to `required=False` is not present in the object to be serialized, it will raise a `KeyError`. Based on my understanding of how DRF works, if a field set to `required=False` has a missing key, it will just skip it and move on. 

http://www.django-rest-framework.org/api-guide/fields/#required

**Comment by terite** [comment]
This sounds like a case fixed in 0.3.0 https://github.com/clarkduvall/serpy/pull/57

**Comment by ahankinson** [comment]
Yep; I will close this now.
