### ISSUE TITLE
No way to omit field from output

### ISSUE THREAD

**Issue by ahankinson** [clarkduvall/serpy#61]
With the reversion of #38, it seems there is currently no way to omit a value from the serialized output. I'm happy to submit a PR, but would appreciate some direction to know what would be an appropriate solution:

 - Add an option to the field, `omit_if_null`
 - Add an option to the serializer initializer, `omit_if_null`
 - ???

**Comment by clarkduvall** [comment]
For your use case do you want to omit None values for all fields, or just omit None for certain fields?

**Comment by ahankinson** [comment]
In the specification I am writing against, a key with a value of 'null' is required to be omitted from the output. 

So if we have `{"foo": "bar", "data": "something"}` the output should be `{"foo": "bar", "data": "something"}`. But if we have `{"foo": "bar", "data": None}` the output should be `{"foo": "bar"}`. 

The behaviour in my use case is to omit the field entirely from the _output_ if the value is `null`. I would have thought `required=False` would trigger that behaviour, but I think there's some uncertainty about what component of the value is "required." Is it "required" on the input data? Or "required" to be in the output serialization?

**Comment by clarkduvall** [comment]
Required means it is required to have the value in the input data. So for example if you were trying to serialize the "data" with a standard `serpy.Field(required=True)`, and you gave it `{}` that would throw an error, but `{'data': None}` would be fine.

I think for your case, you can make a custom serializer that all your serializers will inherit from, that has something like this to filter out None values:
```py
class MySerializer(serpy.Serializer):
    def remove_none(self, d):
        return {k: v for k, v in d.items() if v is not None}

    def to_value(self, instance):
        v = super(MySerializer, self).to_value(instance)
        if self.many:
            return map(self.remove_none, v)
        return self.remove_none(v)
```

**Comment by artefactop** [comment]
I would like to have an option by field like:
```python
class MySerializer(serpy.Serializer):
    foo = serpy.Field(required=False, omit_if_null=True)
```

**Comment by ahankinson** [comment]
Sure, that would work. I guess I was looking for a solution where I didn't have to re-loop back over the output dictionary to filter out the values I didn't want, and instead somehow prevent them from being in the output in the first place.

**Comment by hanshoi** [comment]
I'm having similar use case but instead to have it field by field it could be as a configuration for Serializer or serpy.  What I was thinking that the value could be definable by yourself as there might be situations where you would wan't to have `None` explicitly as value but then a different type for _undefined_.

Would a PR for that kind of thing be appreciated or does adding such configuration just bloat the code?
