### ISSUE TITLE
Is it still under active development?

### ISSUE THREAD

**Issue by rajeshyogeshwar** [clarkduvall/serpy#69]
I am planning to use this library for one of my Django projects. But the last commit I see is more than a month old. I am curious to know if the library is still under active development?

**Comment by clarkduvall** [comment]
Serpy has been pretty stable for awhile. New features are not actively being added, but important bugfixes are still made as needed.

**Comment by rajeshyogeshwar** [comment]
Thank you very much. I have found this to be brilliant and simple.
