### ISSUE TITLE
REST framework compat.

### ISSUE THREAD

**Issue by tomchristie** [clarkduvall/serpy#7]
Couple of easy API changes that'd make serpy directly compatible with `serializer_class = ...` in the generic views with REST framework.

* Accept but ignore the `context` argument.
* Accept but error on the `data` argument, with "serpy serializers do not support input validation".

(Anything else I'm missing?)

Be interested to know if you think that'd be worth doing. If so then we could probably link to `serpy` as an alternative for read-only endpoints.

We'd also want to do a decent job of explaining what use-cases serpy does and doesn't support vs REST framework serializers, but we could address that once we're ready to link to it as an alternative third party package, some obvious points here for later reference:

* Serialization only, no deserialization.
* Unordered.
* No relational types.

**Comment by clarkduvall** [comment]
Yeah this is definitely worth doing. One more API change that would be needed is changing the name of the kwarg name used to pass in the object to `instance` to match DRF (right now its `obj` in serpy).

I'll put up a PR with these changes and have you look it over to see if there's any other compatibility issues.

**Comment by tomchristie** [comment]
Good plan.

**Comment by clarkduvall** [comment]
@tomchristie released the changes in version 0.1.0

**Comment by tomchristie** [comment]
Fab. Welcome to file an issue/pr on rest framework to add this as a third party option. Great stuff!
